upload file to workspace with button
OpenDevin/OpenDevin pull request #1394
Opened 2024-04-26 21:03 UTC by TemryL

partially address https://github.com/OpenDevin/OpenDevin/issues/1379 (upload-only with button) 

starting point to add drag and drop

https://github.com/OpenDevin/OpenDevin/assets/99132608/16a040bd-6e11-4a34-b488-df3723499b8e

2024-04-27 12:16 UTC, rbren commented on opendevin/server/listen.py
> +        file_path = Path(workspace_base) / file.filename
We need to add some validation to `filename` here, to make sure it's not relative to the workspace base

2024-04-27 12:17 UTC, rbren requested changes
This looks rad! Just need a bit of security for filenames

2024-04-28 16:38 UTC, xingyaoww approved these changes
Thanks a lot! This was quick!! LGTM - tested locally and works for me.

2024-04-28 16:39 UTC, xingyaoww commented
@TemryL oh there's some additionaly pylint issue need to be fixed: https://github.com/OpenDevin/OpenDevin/actions/runs/8860701929/job/24349032673?pr=1394

2024-04-28 17:17 UTC, xingyaoww commented
@TemryL You check this doc: https://github.com/OpenDevin/OpenDevin/blob/main/Development.md

Once you run `make build`, i think the pre-commit hooks will be installed for you!

2024-04-29 13:37 UTC, rbren approved these changes

2024-05-01 15:40 UTC, merged

2024-05-01 15:41 UTC, xingyaoww commented
@TemryL Just merged! Thank you for your contribution!

2024-05-01 16:09 UTC, TemryL commented
Thanks!