Update ssh_box.py with adding "Create .bashrc file for the opendevin user"
OpenDevin/OpenDevin pull request #1905
Opened 2024-05-19 21:35 UTC by lixiangtiandashen

The useradd command does not automatically create the .bashrc file when creating the 'opendevin' user, and the following command for backing up .bashrc file in swe_env_box.py will report an error, which is (self.execute('mv ~/.bashrc ~/.bashrc.bak'))

2024-05-19 21:39 UTC, li-boxuan commented
@lixiangtiandashen Did you add `run_as_devin = false` to your `config.toml`?

2024-05-19 22:43 UTC, lixiangtiandashen commented
> @lixiangtiandashen Did you forget to add `run_as_devin = false` to your `config.toml`?
> 
> SWEBench sandbox requires this setting.

I don't. After changing `run_as_devin` to false in config.py, it did pass indeed. But I consider that its default value is true, I think it should also be able to pass with true, so I think it's a bug.

2024-05-19 22:46 UTC, li-boxuan requested changes
It's documented in `evaluation/swe_bench/README.md`. I am guessing it's by design, but I'll let @xingyaoww confirm.

Marking this PR as "change requested" to prevent accidental merge.

2024-05-19 22:51 UTC, lixiangtiandashen commented
> It's documented in `evaluation/swe_bench/README.md`. I am guessing it's by design, but I'll let @xingyaoww confirm.
> 
> Marking this PR as "change requested" to prevent accidental merge.

enen！Thank you, I'm also not sure if there is any special consideration involved.

2024-05-20 10:05 UTC, xingyaoww commented
@lixiangtiandashen I think it is intended that `run_as_devin = false` for SWE-Bench eval -- all the repositories testbeds in the docker are created with root permission, and changing to `opendevin` user could cause unintended consequences. So we should try to set `run_as_devin = false` for SWE-Bench eval. Maybe we can add a warning or error if people try to use `run_as_devin=true` for the eval though.

2024-05-20 10:23 UTC, lixiangtiandashen commented
> @lixiangtiandashen I think it is intended that `run_as_devin = false` for SWE-Bench eval -- all the repositories testbeds in the docker are created with root permission, and changing to `opendevin` user could cause unintended consequences. So we should try to set `run_as_devin = false` for SWE-Bench eval. Maybe we can add a warning or error if people try to use `run_as_devin=true` for the eval though.

Okay, thanks, I understand. In fact, the following steps do require root permission to continue, the swe_entry.sh requires root permission to execute

2024-05-20 10:26 UTC, closed without merging