BioCoder integration
OpenDevin/OpenDevin pull request #2076
Opened 2024-05-27 01:47 UTC by tangxiangru

Integrates BioCoder from https://arxiv.org/abs/2308.16458

2024-05-27 01:48 UTC, lilbillybiscuit commented
### Description:

This pull request is to introduce an evaluation on the BioCoder dataset using agents on OpenDevin. The Biocoder benchmark aims to assess the performance of LLMs on entire repositories related to bioinformatics. It is a challenging full-repository level benchmark that requires both understanding of long-range, inter-class dependencies and domain knowledge.

By evaluating this dataset, we can gain further insights on the performance of LLMs on closed domain (bioinformatics) tasks, as well as their ability to retrieve information and relevant code from a large context window, or the entire repository.

### Key changes:
Added `evaluation/biocoder/run_infer.py`: This file handles execution of the entire Biocoder benchmark using OpenDevin. It loads datasets, runs the agent on each task, and saves the evaluation outputs. Note that we are still 
Added `evaluation/biocoder/biocoder_env_box.py`: This file handles setting up the Biocoder docker environment (which contains many dependencies, libraries, and environments shared across the repositories in Biocoder, including downloading repository files and metadata.

Updated `README.md`: We have updated the README.md to include information about Biocoder, such as the design, challenges, and objectives of the benchmark. Furthermore, we include documentations on executing the framework, an example of the evaluation, and instructions for contributing and customization.

### Related papers:
BioCoder: A Benchmark for Bioinformatics Code Generation with Large Language Models (https://arxiv.org/pdf/2308.16458)

2024-05-27 02:57 UTC, yufansong reviewed
I am little confuse What is `BiocoderSSHBox` for? It seems not called in `run_infer.py`.

2024-05-27 02:57 UTC, yufansong commented on evaluation/swe_bench/swe_env_box.py
> +        sid = f'swe_bench_{swe_instance_id}' + str(uuid.uuid4())  # unique session id
```suggestion
        sid = f'swe_bench_{swe_instance_id}' + str(uuid.uuid4())
```

2024-05-27 02:57 UTC, yufansong commented on evaluation/biocoder/README.md
> +# HumanEvalFix Evaluation with BioCoder
```suggestion
# BioCoder Evaluation with Opendevin
```

2024-05-27 02:57 UTC, yufansong commented on evaluation/biocoder/README.md
> +
Can you add more details about how to run your benchamrk and also add `run_infer.sh`?

2024-05-31 19:19 UTC, neubig commented
@tangxiangru and @lilbillybiscuit , thanks a lot for contributing this! Could you ping us again when the PR is finished and ready for review (including the documentation of how to run)? I'll change it to a draft PR in the meantime.

2024-06-03 02:04 UTC, li-boxuan commented on evaluation/biocoder/run_infer.py
> +            test_result['result'][key.strip()] = value
Please also add metrics, see https://github.com/OpenDevin/OpenDevin/pull/2199 for example

2024-06-08 11:32 UTC, neubig reviewed
Hi @tangxiangru , @lilbillybiscuit, and @li-boxuan -- now that we're done with the main evals for the paper it'd be great to get this merged if you have a moment!

2024-06-08 17:49 UTC, yufansong requested changes
@tangxiangru  @lilbillybiscuit I try to help you fix some comments and add shell script and readme file. But when I try to run your code locally, I actually meet some problem around the `instance` and `BiocoderData`. When I fix one, there are some follow up problems. So I guess you have not push the final version evalution code here.

So please ping me to review when you finish the code. Thanks.

2024-06-09 16:41 UTC, lilbillybiscuit commented
Hi @yufansong and @tangxiangru , I am sorry for the delay, but the final version has been pushed. I am writing a readme but the script can be run with the same arguments as SWE-bench. I am currently writing a more polished readme and it will be pushed shortly.

To answer the previous question, BiocoderSSHBox is a modified version of SWEBenchSSHBox that runs our docker image and all the dependencies (such as fetching the repository archive, testing caches, etc.)

2024-06-10 03:11 UTC, yufansong approved these changes

2024-06-10 03:11 UTC, merged