Auto install Python and netcat
OpenDevin/OpenDevin pull request #2449
Opened 2024-06-15 12:38 UTC by SmartManoj

Helps #2428

2024-06-15 14:17 UTC, SmartManoj commented on Makefile
> +		sudo apt update; \
However, these are prerequisites.

2024-06-15 14:19 UTC, SmartManoj commented on Makefile
> +		sudo apt update; \
how about storing system type in a var in check-system?

2024-06-16 18:37 UTC, neubig commented on Makefile
> +		sudo apt update; \
I use the Makefile on Mac, which does not have apt

2024-06-16 23:13 UTC, SmartManoj commented on Makefile
> +		sudo apt update; \
the file is outdated.

2024-06-20 20:26 UTC, neubig reviewed
@SmartManoj This PR description does not have enough detail for us to review it properly. Could you please update the description to explain what the problem is (e.g. with error logs from the current version), and why this solution may solve it?

Further, I don't think in general that installing a different version of Python than the system uses is a great idea, as some of the other programs in the OS may depend on a specific version. We'll have to think about the best strategy there.

2024-06-21 08:55 UTC, SmartManoj commented
> Further, I don't think in general that installing a different version of Python than the system uses is a great idea, as some of the other programs in the OS may depend on a specific version. We'll have to think about the best strategy there.

`python3` will still point to the system version.

2024-06-22 02:55 UTC, neubig requested changes
I'm sorry, I'm against silently modifying the user's system without their consent. It is much better to inform them about the missing library and allow them to install it themselves.

Since the goal is supporting codespaces, could we set the devcontainer configuration to include these files? https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/adding-a-dev-container-configuration/setting-up-your-python-project-for-codespaces#step-3-modify-your-devcontainerjson-file

2024-06-22 04:12 UTC, SmartManoj commented
> could we set the devcontainer configuration to include these files?

Yes. 

> I'm against silently modifying the user's system without their consent.
Along with the previous, How about getting that too?

2024-07-03 04:15 UTC, neubig requested changes
In the current version of the PR, Makefile still silently modifies the user's system without their consent. Either fix this or close the PR please.

2024-07-03 08:24 UTC, SmartManoj commented
> I'm against silently modifying the user's system

Installing python3.11 (a prerequisite) is an addition and not a modification.

2024-07-03 11:12 UTC, neubig commented
Regardless of what you call it, installing packages on the user's system through sudo without their confirmation is not a behavior I would condone in OpenDevin or any software package.

2024-07-04 15:11 UTC, xingyaoww commented
Also, this installation of Python risks breaking the user's Python environments (e.g., multiple Pythons end up being in ONE system and mess around $PATH). Furthermore, it assumes access to `sudo`.

IMO this PR is not motivated enough (e.g. i don't yet see cases of real user needs here), and probably creates more troublesome / maintenance debt than helping: For example, the user would ask, "Why, after running your command, my system python version is weird, and all my packages are suddenly not accessible?" and it takes the bandwidth of *our* maintainers to address these question.

We already have too many unaddressed problems/issues/things to work on, and I certainly don't hope to add more burden to maintainers in the future.

Therefore, I'm in favor of closing it for the time being. Feel free to reopen if there's a real need for this PR (e.g., user raise issues saying i don't have python in my system AND they don't want to follow existing well-written guide online for installation AND want us to install Python for them, etc).

2024-07-04 15:11 UTC, closed without merging

2024-07-04 15:50 UTC, SmartManoj commented
> "Why, after running your command, my system python version is weird, and all my packages are suddenly not accessible?"

FYI, it won't break the system Python. It will just add `python3.11`; `python3` won't be changed.

2024-07-04 15:53 UTC, xingyaoww commented
Then what's the purpose of doing so? Why can't the user bring their own "python3.11" docker image using [custom sandbox](https://docs.all-hands.dev/modules/usage/custom_sandbox_guide), which IMO would be a simpler solution?

If `python3` won't be changed, then it probably also did not address the user's issue directly.

2024-07-04 16:02 UTC, SmartManoj commented
This is for the app running without docker.