Add GPTSwarm
OpenDevin/OpenDevin pull request #2460
Opened 2024-06-16 12:37 UTC by mczhuge

Sorry for the late response. I have been on vacation for the last 10 days.

I have merged GPTSwarm (ICML 2024 Oral Presentation) into this codebase.

Please see [Paper](https://arxiv.org/abs/2402.16823) and [Code](https://github.com/metauto-ai/GPTSwarm).

However, there are three things that could be further improved:

1. The `agentskill` function currently returns nothing, which makes it hard for GPTSwarm to get a return value. This significantly influences the performance. For example, it can easily achieve 32.07% using original GPTSwarm, but since lacking many file readers, the best performance of OD GPTSwarm is 32.07%.
2. GPTSwarm is stateless, which requires further improvement with others' help. Maybe Q1 could be resolved by this.
3. When I first tried using web navigation skills, I found it returned a very long context that negatively impacted GAIA's performance. Therefore, I did not use it. However, as stated in the original paper, it can largely improve performance.
4. Like in the original GPTSwarm paper, I pay $40 to buy [searchapi](https://www.searchapi.io) for web searching. Any good suggestions (for free and high-quality web searching) here?

Since I will start my internship at Meta tomorrow, I hope others can continue to develop and improve this project.```

Let me know if you need any further adjustments!

2024-06-16 12:43 UTC, tobitege commented
Just about your last question, have you looked at Perplexity.ai? They also have online search and and API etc.

2024-06-16 13:01 UTC, yufansong commented
> The agentskill function currently returns nothing, which makes it hard for GPTSwarm to get a return value. This significantly influences the performance.

Can you explain more on this? What do you mean agentskill function currently returns nothing. 

> but since lacking many file readers

For example what file readers are need?

> GPTSwarm is stateless, which requires further improvement with others' help

Will take a look on this, but I may check your paper firstly. I find you didn't implememnt the `step` function.

> it can easily achieve 32.07% using original GPTSwarm, but since lacking many file readers, the best performance of OD GPTSwarm is 32.07%.

Actually I am thinking, if currently agent skill and web navigation are curently not well done. What is the good point that opendevin can help? I am supprise that opendevin can achive that performance under above problem 🤔 

>  I hope others can continue to develop and improve.

Will help recently when I am free.

2024-06-16 15:03 UTC, yufansong commented
@mczhuge If you have no time in the future, maybe I will directly push on your PR. Or I can only add some comments. WDYT?

2024-06-16 19:15 UTC, neubig requested changes
This looks interesting! I hope we can get this agent incorporated.

However, I am a bit worried about all the dependencies that we would inherit from gptswarm:
https://github.com/metauto-ai/GPTSwarm/blob/ac058b80158027da8ffad8ed0bd464dc952eaa49/pyproject.toml#L23-L66

Maybe we can separate out `gptswarm` to be a different group in poetry that is optionally installed only if we want to use gptswarm.

2024-06-16 19:22 UTC, neubig commented
@mczhuge or @yufansong , would either of you be able to see this to completion now?

2024-06-17 00:44 UTC, mczhuge commented
> Just about your last question, have you looked at Perplexity.ai? They also have online search and and API etc.

Thanks, any simple code demo to use?

2024-06-17 00:56 UTC, mczhuge commented
> > The agentskill function currently returns nothing, which makes it hard for GPTSwarm to get a return value. This significantly influences the performance.
> 
> Can you explain more on this? What do you mean agentskill function currently returns nothing.
> 
> > but since lacking many file readers
> 
> For example what file readers are need?
> 
> > GPTSwarm is stateless, which requires further improvement with others' help
> 
> Will take a look on this, but I may check your paper firstly. I find you didn't implememnt the `step` function.
> 
> > it can easily achieve 32.07% using original GPTSwarm, but since lacking many file readers, the best performance of OD GPTSwarm is 32.07%.
> 
> Actually I am thinking, if currently agent skill and web navigation are curently not well done. What is the good point that opendevin can help? I am supprise that opendevin can achive that performance under above problem 🤔
> 
> > I hope others can continue to develop and improve.
> 
> Will help recently when I am free.

I re-writte the comments a bit: https://github.com/OpenDevin/OpenDevin/pull/2460#issue-2355737537

Regarding "The `agentskill` function currently returns nothing, which makes it hard for GPTSwarm to get a return value. This significantly influences the performance":

I think the mechanism of OD is to output information in the terminal, and then CodeActAgent gets such information as an observation from the terminal. Right? Currently, I do not follow this and just want to directly get a return value from a function. However, I think OD GPTSwarm could also follow the CodeActAgent observation style.

Regarding "For example, what file readers are needed?":

In the original GPTSwarm [readers](https://github.com/metauto-ai/GPTSwarm/blob/main/swarm/environment/tools/reader/readers.py), many different readers are used, but in https://github.com/OpenDevin/OpenDevin/pull/1914 and the following https://github.com/OpenDevin/OpenDevin/pull/2016, some of them have been deleted. This likely influences more than the potentially solvable 2-5 questions, making them unsolvable in GAIA.

Regarding "GPTSwarm is stateless" and "I find you didn't implement the `step` function":

I think OD GPTSwarm could fully follow the agenthub style (it may not be hard), but I am personally not 100% familiar with this, so I think help is needed here.

Regarding "if currently agent skill and web navigation are not well done":

I think the current web navigation is good but specific to some benchmarks. For GAIA or many applications, just returning compressed but informative observations is enough.

2024-06-17 01:01 UTC, mczhuge commented
> @mczhuge If you have no time in the future, maybe I will directly push on your PR. Or I can only add some review comments. WDYT?

I have time to discuss more and may also contribute some code, but currently, you know, the first month as an intern may require some time to focus. By the way, if you could help push this PR forward, that would be great. Two potential good things may happen in OpenDevin if we finish this PR:

1. Graph-based agent evolution.
2. Potential to evolve the OpenDevin agent similarly to GPTSwarm, giving the OD framework greater potential.

2024-06-17 01:06 UTC, mczhuge commented
> This looks interesting! I hope we can get this agent incorporated.
> 
> However, I am a bit worried about all the dependencies that we would inherit from gptswarm: https://github.com/metauto-ai/GPTSwarm/blob/ac058b80158027da8ffad8ed0bd464dc952eaa49/pyproject.toml#L23-L66
> 
> Maybe we can separate out `gptswarm` to be a different group in poetry that is optionally installed only if we want to use gptswarm.

Hi @neubig , some of them has already merged in OD. See https://github.com/OpenDevin/OpenDevin/pull/1914 and https://github.com/OpenDevin/OpenDevin/pull/2016. Currently, we only need to improve the usage.

2024-06-17 04:06 UTC, tobitege commented
> > Just about your last question, have you looked at Perplexity.ai? They also have online search and and API etc.
> 
> Thanks, any simple code demo to use?

There is an actual Python package that would make it easier:
https://pypi.org/project/PerplexiPy/

Their sample code on that page reads like this:
```Py
client = PerplexityClient() \
print(client.query('What is the meaning of 42?') \
for result in client.queryStreamable('List of all US presidents'): \
    print(result)
```

Hope, this helps. 😃

2024-06-17 12:52 UTC, yufansong commented
> @mczhuge or @yufansong , would either of you be able to see this to completion now?

If @mczhuge have no time, I am glad to take this task.

2024-06-17 20:08 UTC, mczhuge commented
> > @mczhuge or @yufansong , would either of you be able to see this to completion now?
> 
> If @mczhuge have no time, I am glad to take this task.

Great Yufan! Please go ahead, I am on the intern orientation

2024-06-17 21:39 UTC, tobitege commented on opendevin/runtime/plugins/agent_skills/agentskills.py
>      'OPENAI_API_KEY', os.getenv('SANDBOX_ENV_OPENAI_API_KEY', '')
Within the sandbox, this would be exported again without the prefix, i.e. as "OPENAI_API_KEY".

2024-07-03 04:19 UTC, neubig commented
@yufansong (CC @mczhuge) : just checking in on this because it's been two weeks without activity, are we still working on this? I'm happy to run an evaluation when we get to that point.

2024-07-03 04:49 UTC, yufansong commented
> @yufansong (CC @mczhuge) : just checking in on this because it's been two weeks without activity, are we still working on this? I'm happy to run an evaluation when we get to that point.

Just finish my business trip and I am little busy in past two week. Not too much progress now, but will launch the work recently 😁

2024-07-03 04:55 UTC, neubig commented
No worries! Just checking in on all our open issues.

2024-08-06 22:59 UTC, yufansong commented
After discussion with @xingyaoww and @li-boxuan, we think it is better to put this work into a seperate branch firstly in opendevin repo. It will take lots of efforts to refactor the whole agent into opendevin's codebase which should be our top priority. 
Put it in seperate branch can make sure anyone interested in this work can run the evaluation on benchmark.

2024-08-11 06:02 UTC, merged