Fix ValueError: "invalid literal for int() with base 10"
OpenDevin/OpenDevin pull request #2707
Opened 2024-06-30 18:40 UTC by tansautn

This fix #2702 .

to avoid passed a string not only contain number. Just added regex match then simulate success code.

2024-06-30 18:57 UTC, tobitege requested changes
Holding this off for now.
The issue might be elsewhere, the code you touch is expecting an exit code and should not require this change.

See https://github.com/OpenDevin/OpenDevin/pull/2642

2024-07-01 06:01 UTC, iFurySt commented
it looks like it's trying to get the exit code before the command has finished executing. so get the stream output and try to parse it as an exit code

2024-07-01 13:00 UTC, enyst commented
> Holding this off for now. The issue might be elsewhere, the code you touch is expecting an exit code and should not require this change.
> 
> See #2642

Good call. I've hit this one too during evals, it's pretty bad. 😥

2024-07-01 13:09 UTC, tobitege commented
> Good call. I've hit this one too during evals, it's pretty bad. 😥

It'd be great, if you have any logs still available, where this occurs. It's not immediately clear to me, if this is one or two different locations (one during plugin initialization as in this issue, and run_ipython) that reference an exit code.

2024-07-01 17:26 UTC, enyst commented
> > Good call. I've hit this one too during evals, it's pretty bad. 😥
> 
> It'd be great, if you have any logs still available, where this occurs. It's not immediately clear to me, if this is one or two different locations (one during plugin initialization as in this issue, and run_ipython) that reference an exit code.

@tobitege 
If it helps, these are log notes that I took during the run, where I cut and pasted the exact errors on the fly: https://gist.github.com/enyst/d25f310fb07b397abc420a8318c03a42

I might still find some full logs somewhere too.

2024-07-01 20:01 UTC, tobitege commented
Closing this in favor of merged https://github.com/OpenDevin/OpenDevin/issues/2702
Please try with current main. Thanks, though, for putting up this PR in the first place! 👍

2024-07-01 20:01 UTC, closed without merging